### ISSUE TITLE
Confused about the output 

### ISSUE THREAD

**Issue by kaosat-dev** [mikolalysenko/convex-hull#1]
Hello @mikolalysenko  ! 
In the example you give, for the input in the example the output is 
`[[0, 1], [1, 2], [2, 0]]`
While I would expect it to be 
`[[0, 0], [1, 0],[0, 1]]`
As there are no points outside the 0-1 range in the inputs,  how can a convex hull have anything outside of it . am I missing something ? 

Thanks in advance !

**Comment by EvenAR** [comment]
The output are vertex indices for each line segment. I.e `[0,1]` means that the first line segment goes from index 0 in the input array (`[0,0]`) to index 1 (`[1,0]`). The second line goes from index 1 (`[1,0]`) to 2 (`[0,1]`), and so on. 

```
[0, 1] = [[0,0], [1,0]]
[1, 2] = [[1,0], [0,1]]
[2, 0] = [[0,1], [0,0]]
```

**Comment by kaosat-dev** [comment]
Hi @EvenAR  thanks a lot for clarifying ! That makes sense !
I will close this, it means it works as expected. 👍
